#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

if (PHP_VERSION_ID < 80200) {
    fwrite(STDERR, "PHP 8.2 or higher is required.
");
    exit(1);
}

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
